### PR TITLE
Updated some texts in features. Created features for UI model plugins

### PR DESCRIPTION
**Pull request by renetrefft**
I've packaged the UI model plugins not in the related model features as demanded in issue #405, but in new UI model features. This decision doesn't mix up the UI components with our logic. If a user installs only a model from our P2, no UI components will be installed.

### CODE REVIEW

**Comment by timsanwald** [comment]
I thought this handles just the features, but there are deleted files of PCTL?

**Comment by philippniethammer** [comment]
The model features already contain ui parts with the two editors.  Why do we need to open a separate ui feature for one package, now? And probably add dependencies to them in the model feature because we need it... 

Just my 2 cents.

**Comment by renetrefft** [comment]
The deleted PCTL files are just xtend-gen stuff that will be generated during workspace building respectively at build time.

**Comment by renetrefft** [comment]
The UI model plugins are now packaged in the model features.

**Pull request closed without merging**
